### ISSUE TITLE
При вводе некоторых слов из банлиста выводит ошибку

### ISSUE THREAD

**Issue by NosferatuZoddd** [link1107/DonationExecutor#32]
Если ввести например "nigg" или "нигг" или "пидд" и т.д. выкидывает следующее:
```
[DonationExecutor] Task #3 for DonationExecutor v0.3.4 generated an exception
java.lang.StringIndexOutOfBoundsException: String index out of range: 4
        at java.lang.StringLatin1.charAt(StringLatin1.java:48) ~[?:?]
        at java.lang.String.charAt(String.java:1512) ~[?:?]
        at igorlink.service.Utils.isBlackListed(Utils.java:219) ~[DonationExecutor-0.3.4.jar:?]
        at igorlink.donationexecutor.Executor.DoExecute(Executor.java:51) ~[DonationExecutor-0.3.4.jar:?]
        at igorlink.donationexecutor.playersmanagement.donationalerts.DonationAlertsToken.executeDonationsInQueues(DonationAlertsToken.java:46) ~[DonationExecutor-0.3.4.jar:?]
        at igorlink.donationexecutor.playersmanagement.StreamerPlayersManager$1.run(StreamerPlayersManager.java:29) ~[DonationExecutor-0.3.4.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-187]        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-187]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
Иногда выкидывает похожую ошибку, но немного другую если присмотреться:
```
java.lang.StringIndexOutOfBoundsException: index 4, length 4
        at java.lang.String.checkIndex(String.java:4560) ~[?:?]
        at java.lang.StringUTF16.checkIndex(StringUTF16.java:1624) ~[?:?]
        at java.lang.StringUTF16.charAt(StringUTF16.java:1421) ~[?:?]
        at java.lang.String.charAt(String.java:1514) ~[?:?]
        at igorlink.service.Utils.isBlackListed(Utils.java:219) ~[DonationExecutor-0.3.4.jar:?]
        at igorlink.donationexecutor.Executor.DoExecute(Executor.java:51) ~[DonationExecutor-0.3.4.jar:?]
        at igorlink.donationexecutor.playersmanagement.donationalerts.DonationAlertsToken.executeDonationsInQueues(DonationAlertsToken.java:46) ~[DonationExecutor-0.3.4.jar:?]
        at igorlink.donationexecutor.playersmanagement.StreamerPlayersManager$1.run(StreamerPlayersManager.java:29) ~[DonationExecutor-0.3.4.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-187]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-187]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
При этом донат не выводится на экран и не активируется действие за донат

**Comment by link1107** [comment]
fixed в 0.3.5
