### ISSUE TITLE
При первом запуске ошибка 

### ISSUE THREAD

**Issue by MarkG1M** [link1107/DonationExecutor#33]
При самом первом запуске сервера с плагином выдает такую ошибку:
```
java.lang.NullPointerException: Cannot invoke "igorlink.donationexecutor.playersmanagement.StreamerPlayersManager.stop()" because "this.streamerPlayersManager" is null
        at igorlink.donationexecutor.DonationExecutor.onDisable(DonationExecutor.java:45) ~[DonationExecutor-0.3.4.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:514) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.clearPlugins(SimplePluginManager.java:592) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.reload(CraftServer.java:998) ~[paper-1.18.1.jar:git-Paper-187]
        at org.bukkit.Bukkit.reload(Bukkit.java:857) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897) ~[paper-1.18.1.jar:git-Paper-187]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:860) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:507) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:481) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-187]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
В последующие запуски/перезапуски ничего не выводится

**Comment by link1107** [comment]
[0.3.4 fixed.zip](https://github.com/link1107/DonationExecutor/files/8053093/0.3.4.fixed.zip)

Попробуй плиз эту версию и отпиши, будет ли работать

**Comment by NosferatuZoddd** [comment]
> [0.3.4 fixed.zip](https://github.com/link1107/DonationExecutor/files/8053093/0.3.4.fixed.zip)
> 
> Попробуй плиз эту версию и отпиши, будет ли работать

Теперь норм работает, однако ошибка #32 осталась

**Comment by NosferatuZoddd** [comment]
> > > [0.3.4 fixed.zip](https://github.com/link1107/DonationExecutor/files/8053093/0.3.4.fixed.zip)
> > > Попробуй плиз эту версию и отпиши, будет ли работать
> > 
> > 
> > Теперь норм работает, однако ошибка #32 осталась
> 
> попробуй 0.3.5 в релизах

Теперь все идеально работает
